rootProject.name = "Space X App"
include (":app")
include(":core-ui")
include(":core-designsystem")
include(":core-network")
include(":core-data")
include(":core-common")
include(":core-model")
include(":core-database")
include(":feature-rockets")
include(":feature-crew")
include(":feature-history-events")
include(":feature-rocket-detail")
include(":feature-launchpads")
include(":feature-launchpad-detail")
